# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:
    apt:
        packages:
            - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.9

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cd addons/sourcemod/scripting/
    # - wget "https://raw.githubusercontent.com/50DKP/FF2-Official/master/addons/sourcemod/scripting/include/freak_fortress_2.inc" -O include/freak_fortress_2.inc
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O include/morecolors.inc
    - chmod +x spcomp
script:
    - ./compile.sh serverside_achievement.sp

    - mkdir compiled/sa_subplugins
    - ./compile.sh sa_subplugins/*.sp
    # - mv compiled/*.smx compiled/sa_subplugins/*.smx
    # - wget "https://raw.githubusercontent.com/TeamPotry/FF2_Fork/2.2/sourcemod/scripting/include/freak_fortress_2.inc" -O include/freak_fortress_2.inc

# Releases
before_deploy:
    - cd ../
    - mkdir serverside_achievement serverside_achievement/addons serverside_achievement/addons/sourcemod serverside_achievement/addons/sourcemod/configs serverside_achievement/addons/sourcemod/configs/serverside_achievement serverside_achievement/addons/sourcemod/data serverside_achievement/addons/sourcemod/data/serverside_achievement serverside_achievement/addons/sourcemod/scripting serverside_achievement/addons/sourcemod/scripting/serverside_achievement serverside_achievement/addons/sourcemod/scripting/sa_subplugins serverside_achievement/addons/sourcemod/scripting/include serverside_achievement/addons/sourcemod/plugins serverside_achievement/addons/sourcemod/plugins/sa_subplugins serverside_achievement/addons/sourcemod/translations
    - mv configs/serverside_achievement serverside_achievement/addons/sourcemod/configs/serverside_achievement
    - mv data/serverside_achievement serverside_achievement/addons/sourcemod/data/serverside_achievement

    - mv scripting/serverside_achievement.sp serverside_achievement/addons/sourcemod/scripting/serverside_achievement.sp
    - mv scripting/compiled/serverside_achievement.smx serverside_achievement/addons/sourcemod/plugins/serverside_achievement.smx
    - mv scripting/compiled/sa_subplugins serverside_achievement/addons/sourcemod/plugins/sa_subplugins

    - mv translations/serverside_achievement.txt serverside_achievement/addons/sourcemod/translations/
    - zip -rq serverside_achievement serverside_achievement
    - tar -czf serverside_achievement.tar.gz serverside_achievement
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file:
        - serverside_achievement.zip
        - serverside_achievement.tar.gz
        - serverside_achievement/addons/sourcemod/plugins/serverside_achievement.smx
        - serverside_achievement/addons/sourcemod/scripting/serverside_achievement.sp
    skip_cleanup: true
    on:
        repo: Nopied/serverside_achievement
        all_branches: true
        tags: false

# Notifications
notifications:
    email: false
